### ISSUE TITLE
load balance nginx and consul 

### ISSUE THREAD

**Issue by komuisam** [pabpereza/pabpereza#111]
**¿Qué tienes en mente? ¿Qué temáticas te gustaría que tratáramos?**
Me gustaria ver como hacer los balanceadores de carga con nginx pero con un sistema de descubrimiento consul para dinamizar que al levantar los microservicios el balanceador tome ese microservicio para balancear, tambien como levantar mas contenedores si estan full de peticiones que herramienta usarias para lebbantar esos contenedores.

**Comment by komuisam** [comment]
Dale estas son las caracteristicas generales: 

- Digamos que tengo una plataforma donde el  frond esta en nextjs, que es como udemy donde los usuarios interactuan y ven cursos.

- Por otra parte tengo una estructura distribuida de microservicios en nestjs y nodejs:
- Microservicio donde tengo la estructura del curso js, ejs, css, ejemplo un curso completo de matematica.
- Microservicio de envio de interaccion del usuario con ese curso en los ejercicios de matematica, las respuestas correctas incorrectas y tal.

Esto digamos que es a la escala de unos 40mill usuarios si monto uno de cada uno se cae.
Como podria  hacer para desplegar algo como eso, yo tengo una idea de como hacer balanceadores con haproxy y consul pero la parte de autoescalado y healing de servicios... no lo tengo claro.

Tenia la idea de meter consul, haproxy mas kubernetes pero vi que el ya tiene los balanceadores de carga, auto escalado y tal por eso ahora estoy entre dos cosas, olvidarme de lo que tengo y meterme solo con kubernetes que no tengo ni idea o buscar alternativas para esa parte y quedarme con los que ya controlo un poco, ademas que los tutos no es que ayuden mucho.

**Comment by pabpereza** [comment]
La verdad es que desconozco el sistema de licencias de Cónsul. Personalmente lo montaría sobre Kubernetes, ya solo eso cumpliría todos los requisitos que necesitas. Es verdad que igual tiene un poco más de curva de aprendizaje, pero a la larga y para escalar una aplicación seguramente sería lo mejor.
