### ISSUE TITLE
Gestión de webs+email con Docker

### ISSUE THREAD

**Issue by Rauljauregi** [pabpereza/pabpereza#132]
Mola mucho el curso de Docker, enhorabuena. 
Tengo una petición o sugerencia. En mi caso tengo unas cuantas webs (WordPress), e emails  de las webs, en un VPS, y además todas mis webs pasan por CloudFlare.  

Quiero dar el paso a gestionar todo con contenedores. Y la verdad que no sé ni por donde empezar, ni qué hosting elegir. Ya uso Docker en algunas cosas, pero siempre en local, me da yuyu usar Google Cloud (ya tengo cuenta etc, pero me da miedo que me de un susto con alguna factura mensual).

Estaría genial una serie de videos para containerizar estas webs y después gestionarlas. Para automatizar los backups, etc...

Creo que esta es una necesidad bastante gente tendrá. Bueno enhorabuena por el curso

**Comment by pabpereza** [comment]
Muchas gracias por el apoyo, me alegra que te este gustando el curso.

Me parece una sugerencia e idea genial, me la apunto para hacer un vídeo más adelante. Personalmente gestiono mis servidores personales con NPM (Node Proxy Manager) y Docker y creo que podría ser interesantes este enfoque de hostings compartidos.

Un saludo y gracias por contribuir.

**Comment by Rauljauregi** [comment]
Muchas gracias!!

**Comment by pabpereza** [comment]
Cierro este y sigo en una tarea más genérica, espero que sea el próximo vídeo. Gracias por la sugerencia, un saludo.

**Comment by Rauljauregi** [comment]
Gracias!
