### ISSUE TITLE
Error con ollama y Anythinllm en docker

### ISSUE THREAD

**Issue by halvarez22** [pabpereza/pabpereza#133]
Hola, espero puedas apoyarme, te cuento, estoy instalando un docker desktop usando wsl en windows, descargo imagenes y creo container usando archivos dockerfile y docker-compose.yml, estoy instalando ollama y anythingllm para tener un LLM open source privado, todo va de ma ravilla, ollama esta corriendo, el LLM tambien, Anything tambien corre al 100!!  al configfurar anything ve perfectamente a ollama, carga el modelo y listo, presenta el prompt, sin embargo, al intentar interaccionar con el LLM siempre recibo este error! "Could not respond to message. an error ocurred while streaming response. network error" sabes si se debe a un error de configuracion de docker?

**Comment by pabpereza** [comment]
Buenas! Pues no tengo ni idea porque nunca he utilizado, he estado viendo esa guía https://github.com/Mintplex-Labs/anything-llm/blob/master/docker/HOW_TO_USE_DOCKER.md  

Revisa bien la parte de windows. También comparte por aquí el docker compose a ver si vemos algún error juntos.

**Comment by halvarez22** [comment]
Mil gracias Pablo! te comparto el compose, ojala encuentres el error!
abrazo!

*ATENTAMENTE:*

*Ing. Hector Alvarez*

*Gerente General*

[image: ***@***.***

*Roble de Jerez #1939 **||**Col. Jardines de Jerez II sec*

*León, Guanajuato, México **||**C.P. 37371**||**Tel: (477) 724.1148**||*

*www.gruposertei.net <http://www.gruposertei.net/> **||*[image:
http://t3.gstatic.com/images?q=tbn:ANd9GcTs16v3rONbvMsOMYJ2nKrDQSRORDA66Q9wnqFZIs73Pa6cZ3WSvQ]
*gruposertei**||[image: twitter] **@**gruposertei*



*AVISO LEGAL *

La información contenida en este mensaje es privilegiada y confidencial. Si
el lector de la misma no es a quien inicialmente se destinó, considérese
notificado de la prohibición de distribuir, reenviar, duplicar o copiar
esta información. Si usted está recibiendo este mensaje por error, por
favor notifique inmediatamente al remitente y borre este mensaje de su
equipo de cómputo, teléfono móvil o tablet.

**Comment by pabpereza** [comment]
Disculpa, se me pasó el error. En cualquier caso, si estas adjuntando al email, esta fallando. Esto es un issue de GitHub. Lo mejor sería que pegaras el compose en texto plano.
