### ISSUE TITLE
GUI con Docker

### ISSUE THREAD

**Issue by hec7orci7o** [pabpereza/pabpereza#19]
Hacer la variación del navegador para poder acceder a la interfaz gráfica de Kali.

**Comment by pabpereza** [comment]
- Buenas Héctor, gracias por la sugerencia, cuando tenga tiempo haré un video sobre el tema. Gracias y un saludo.

**Comment by pabpereza** [comment]
Creado en este vídeo. https://youtu.be/jqEmODnljYs
