### ISSUE TITLE
Registro propio de docker

### ISSUE THREAD

**Issue by Santalinos** [pabpereza/pabpereza#2]
Hay alguna manera de crear un registro propio en Docker que se pueda almacenar por ejemplo en una llave usb para llevarlo de un sitio a otro?  Quiero evitar instalar un servidor propio real. 
Me pregunto si se puede copiar el registro propio docker de mi equipo a una llave usb y hacer push-pull de las imágenes a-desde el usb.
De poderse, serías más cómodo que exportar las imágenes de mi repositorio para importarlas en el repositorio del otro equipo.

Espero haberlo explicado bien.

Un saludo.

**Comment by pabpereza** [comment]
Buenas @Santalinos , te has explicado correctamente. Haré un video para explicar como llevarte las imágenes en USB u otros medios alternativos.

¡Gracias por colaborar sugiriendo contenidos!

**Comment by pabpereza** [comment]
Buenas @Santalinos , en este vídeo trato el tema https://youtu.be/P2CGj6aSg6w y ya he metido en este repositorio el script creado. Espero que conteste tus dudas y sea útil a la comunidad.

**Comment by Santalinos** [comment]
Fantástico Pablo!

Qué interesante sería no perder el tageo de las máquinas cuando se hace copiar de todo. O quizá, hacerla de una en una dentro del script con un bucle. Así, no perdemos nada. Puesto que podemos hacer algo como un "docker images | cut - "... coger en nombre o el ID de la imagen y hacer copias de todas las imágenes pero, de una en una. Para recuperarlas todas de una vez, otro bucle. ¿Qué opinas?

**Comment by pabpereza** [comment]
Sería lo idóneo, eres libre de modificar el script y hacer un pull request. Igualmente, luego saco un rato y lo adapto con la mejora que propones

**Comment by Santalinos** [comment]
Ok, en cuanto tenga un rato hoy, le echo un ojo y hago un pull.

**Comment by Santalinos** [comment]
Hola Pablo.

En lugar de modificar lo que tú has escrito. Adjunto dos archivos:

- **imexport.sh**: exporta todas las imágenes al directorio actual. 
- **imimport.sh**: importa todas las imágenes salvada de nuevo al repositorio.

El exportar crea un archivo con el Repo:tag de cada imagen y, al importarlo de nuevo, se basa en el nombre para recuperar Repositorio y Tag.

Es verdad, que se puede completar más ambos scripts para añadir validaciones. Sólo hace falta un poco de tiempo más. ;)

[importar_exportar_imagenes.zip](https://github.com/pabpereza/pabpereza/files/6970307/importar_exportar_imagenes.zip)

**Comment by pabpereza** [comment]
Buenas @Santalinos , me gusta mucho tu enfoque, además has bajado a meter tambien los tags luego los miro con profundidad. Para poder hacer un pull request primero tienes que hacer un fork, luego modificas a tus anchas y por último vienes a este repo y en la pestaña de pull request, solicitas uno y seleccionas tu fork

**Comment by pabpereza** [comment]
Ahora que me he fijado @Santalinos , el fork lo tienes que hacer del repo kali-utils jeje este solo tiene una referencia hace el

**Comment by pabpereza** [comment]
Bueno, doy por cerrada esta tarea. Continuaré el hilo en esta https://github.com/pabpereza/pabpereza/issues/3 para crear to propio repositorio. Gracias @Santalinos por la colaboración.

**Comment by Santalinos** [comment]
Un placer!
