### ISSUE TITLE
DOCKER ESCAPE

### ISSUE THREAD

**Issue by sec-balkan** [pabpereza/pabpereza#4]
Hola Pablo;

Podrías hablar sobre técnicas de Docker Breakout, o malas configuraciones que podrían darse para saltar fuera del contenedor, así como vulnerabilidades de Docker.

Aunque no tiene por qué ser de Docker, también puedes meter LXD, LXC...

Un saludo 🙂

**Comment by pabpereza** [comment]
Hola Balkan, gracias por tu feedback! Me parece un tema muy interesante y hablaré de él en próximos videos.

**Comment by pabpereza** [comment]
Dentro de 2 vídeos haré este. Quiero mantener cierto orden lógico además que este tema me requiere algo más de investigación por abordarlo de la forma más completa.

**Comment by pabpereza** [comment]
@sec-balkan se que han pasado muchos meses pero ya casi lo tengo. No me he visto preparado para hacer esto hasta ahora y aún lo tengo a medio documentar. Espero para la semana que viene poder terminar de documentarlo y grabar las pruebas en vivo. [Escalada de privilegios en contenedores](https://pabpereza.dev/docs/pentesting/privilegios/contenedores/) A tiempo estas si quieres aportar algo que se me haya pasado. De momento, voy a centrarme en los fallos de mala configuración para que no sea demasiado avanzado y una herramienta de enumeración. Iré sacando más vídeos al respecto.

**Comment by pabpereza** [comment]
Cerrado hasta nuevos episodios
