### ISSUE TITLE
Pentest / CTF desde un contenedor docker

### ISSUE THREAD

**Issue by pwnhun73r** [pabpereza/pabpereza#42]
Te agradezco por lo que compartes en los videos, he aprendido de ellos.
La idea que se me ocurrio es sobre un video donde se pueda ver desde la enumeracion hasta obtener una shell reversa en el contenedor, aplicable a cualquier plataforma (HTB, THM, una imagen docker vulnerable, etc)

**Comment by pabpereza** [comment]
Muchas gracias por el apoyo, me parece una gran idea para hacer un vídeo. Lo añado a la lista de tareas para tenerlo en cuenta para los próximos. Un saludo!
