### ISSUE TITLE
Aligerar contenedores con python

### ISSUE THREAD

**Issue by dpolob** [pabpereza/pabpereza#64]
Hola Pablo

Te paso por aqui los archivos de los que te hable en el comentario de tu último vídeo. Como te comenté las librerías que instalo no me da la impresión que sea muy pesada. Realizando un docker inspect he visto que todo el grueso esta en conda/pkgs, pero 2.5 Gb, madre mía... con un docker clean algo se arregla pero...

No he probado como queda con pip, pero es que la libreria gdal conviene instalarla con conda porque con pip es un dolor. Yo siempre instalo python3.8-slim-buster e instalo miniconda (un error que ya no vuelvo a cometer, porque luego activar conda es un dolor). Probé con miniconda, como indicó alguien en Youtube, pero los resultados son los mismos.

No tenia acceso a los archivos por lo que te los pongo aquí de memoria, ya lo siento...

Gracias y saludos!!

Diego Polo

DOCKERFILE

FROM continuumio/miniconda3:latest

# Install base utilities
RUN apt-get update \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ADD requirements.txt .

RUN conda install -c conda-forge --file requirements.txt
CMD /bin/bash

REQUIREMENTS.TXT
python==3.8
gdal==3.4.1
cdsapi==0.5.1
pygrib==2.1.4
numpy==1.24.1
python-dotenv==0.21.1

**Comment by ipedrazas** [comment]
Esa version de miniconda lleva python 3.10, pero en requirements le metes 3.8 `ARG CONDA_VERSION=py310_22.11.1-1`


https://hub.docker.com/layers/continuumio/miniconda3/latest/images/sha256-b447e10d864316cd76707ff637d53c7e73ec03442e83b8cf01f9feae8c7dacbc?context=explore

Si haces el docker build con los requirements sin la 3.8 la imagen pesa 670MB:

```
FROM continuumio/miniconda3:latest

COPY requirements.txt .

RUN <<EOF
conda install -c conda-forge --file requirements.txt
EOF
```

Requirements:
```
gdal==3.4.1
cdsapi==0.5.1
pygrib==2.1.4
numpy==1.24.1
python-dotenv==0.21.1
```

El primer `RUN` no te hace falta, si quieres tener una imagen actualizada, usa `master` https://hub.docker.com/layers/continuumio/miniconda3/master/images/sha256-63d1a6183e57fa45b78d4d7876603d4541c201dc95fe8c3c3e5e4a66159af023?context=explore

El ultimo `CMD` tampoco hace falta.

**Comment by dpolob** [comment]
Hola

Pues muchas gracias... pensaba que no habría ninguna version de python 
por debajo y que por eso había que instalar una. Gracias por el cable

Saludos

**Comment by dpolob** [comment]
Disculpa aprovecho este canal para presentaros PythonLaRioja.
[https://www.eventbrite.es/e/entradas-charla-1-marzo-2023-569867146977](https://www.eventbrite.es/e/entradas-charla-1-marzo-2023-569867146977)
Igual os interesa y si nos ayudáis a difundirlo perfecto!!!

**Comment by pabpereza** [comment]
Gracias por compartir Diego, creo que podré estar la última media hora al menos ;)

**Comment by pabpereza** [comment]
He creado un repositorio de ejemplos multi-stage en diferentes tecnologías por si queréis contribuir ahí. https://github.com/pabpereza/multi-stage-containers-examples e iré haciendo vídeos del tema. Cualquier aporte en bienvenido! Cierro este hilo. Un saludo!
